name: Deploy Docker Container

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      registry_name:
        required: true
        type: string
      registry_username:
        required: true
        type: string
      registry_password:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true
      DIGITALOCEAN_APP_ID:
        required: true
      DISCORD_CI_WEBHOOK:
        required: true

jobs:
  deploy:
    name: Deploy Container
    # Available Runners: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest
    # Available Docker Images: https://hub.docker.com/_/swift/
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      # Docker Actions: https://github.com/marketplace/actions/build-and-push-docker-images#path-context
      # By default, this action uses the Git context so you don't need to use the actions/checkout action to check out the repository because this will be done directly by BuildKit.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_username }}
          password: ${{ inputs.registry_password }}

      - name: Build Image and Push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ inputs.registry}}/${{ inputs.registry_name}}/${{ inputs.image_name }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
