name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  registry_password: secrets.GITHUB_TOKEN
  # DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  deploy_github:
    name: Deploy to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Build and Deploy Container
        uses: bdrelling/instruments.fyi/.github/actions/deploy-cintainer@${{ github.sha }}
        with:
          registry: ghcr.io
          registry_name: ${{ github.actor }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          image_name: instruments-fyi:latest

  # deploy_digitalocean:
  #   uses: ./.github/workflows/build_and_deploy_docker_container.yml
  #   # uses: bdrelling/ci/.github/workflows/deploy_container_digitalocean.yml@main
  #   secrets: inherit
  #   with:
  #     registry: registry.digitalocean.com
  #     registry_name: brian-drelling
  #     registry_username: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}
  #     registry_password: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}
  #     image_name: instruments-fyi:latest
