name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    uses: ./.github/workflows/deploy_container_github.yml
    # uses: bdrelling/ci/.github/workflows/deploy_container_digitalocean.yml@main
    secrets: inherit
    with:
      registry: ghcr.io
      registry_name: bdrelling
      registry_username: ${{ github.actor }}
      registry_password: ${{ env.GITHUB_TOKEN }}
      image_name: instruments-fyi
