name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    uses: bdrelling/workflows/.github/workflows/deploy_container_digitalocean.yml@main
    secrets: inherit
    with:
      registry_name: brian-drelling
      image_name: instruments-fyi
