name: Deploy

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy_website.yml'
      - 'Plugins/**'
      - 'Public/**'
      - 'Snippets/**'
      - 'Sources/**'
      - 'Tests/**'
      - '**.swift'
      - 'Package.resolved'
      - 'Dockerfile'
      - 'docker-compose.yml'

jobs:
  prepare:
    name: Prepare
    uses: bdrelling/ci/.github/workflows/deploy_to_digitalocean.yml@main
    secrets: inherit
    with:
      registry_name: brian-drelling
      image_name: instruments-fyi:latest
