name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy_github:
    uses: ./.github/workflows/build_and_deploy_docker_container.yml
    # uses: bdrelling/ci/.github/workflows/deploy_container_digitalocean.yml@main
    secrets: inherit
    with:
      registry: ghcr.io
      registry_name: bdrelling
      registry_username: ${{ github.actor }}
      registry_password: ${{ env.GITHUB_TOKEN }}
      image_name: instruments-fyi:latest
  # deploy_digitalocean:
  #   uses: ./.github/workflows/build_and_deploy_docker_container.yml
  #   # uses: bdrelling/ci/.github/workflows/deploy_container_digitalocean.yml@main
  #   secrets: inherit
  #   with:
  #     registry: registry.digitalocean.com
  #     registry_name: brian-drelling
  #     registry_username: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}
  #     registry_password: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}
  #     image_name: instruments-fyi:latest
