name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  registry_password: secrets.GITHUB_TOKEN
  # DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  deploy_github:
    name: Deploy to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy Container
        uses: bdrelling/instruments.fyi/.github/actions/deploy-container@main
        with:
          registry: registry.digitalocean.com
          registry_name: brian-drelling
          registry_username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          registry_password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          image_name: instruments-fyi:latest
