name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/tests.yml'
      - 'Plugins/**'
      - 'Snippets/**'
      - 'Sources/**'
      - 'Tests/**'
      - '**.swift'
      - 'Package.resolved'

jobs:
  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test.yml@main
    secrets: inherit
    with:
      scheme: InstrumentsFYI
      subcommand: build
      platforms: macOS Linux
      swift-versions: 5.6
