name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # Add paths!

jobs:
  test:
    uses: bdrelling/workflows/.github/workflows/swift_test_vapor_website.yml@main
    secrets: inherit
    with:
      scheme: InstrumentsFYI-Package
